- 파이썬 라이브러리(Python Library)?

- 파이썬 프로그래밍 언어에서 특정 기능을 수행하기 위해 미리 작성된 코드의 모음입니다. 
- 이 라이브러리들은 개발자가 특정 기능을 구현할 때, 반복적으로 코드를 작성할 필요 없이 이미 만들어진 기능을 사용하여 개발 시간을 단축하고 코드를 간결하게 작성할 수 있게 해줍니다.
- 표준 라이브러리(Standard Library): 파이썬 설치 시 기본적으로 제공되는 라이브러리입니다. 파일 입출력, 문자열 처리, 수학 계산, 네트워크 통신, 날짜 및 시간 처리 등 기본적인 기능들을 제공합니다. 예시로 os, sys, math, datetime 등이 있습니다.
- 서드파티 라이브러리(Third-Party Library): 표준 라이브러리에 포함되지 않은 기능을 추가로 제공하는 라이브러리로, 파이썬 커뮤니티나 기업이 개발하여 공개한 라이브러리입니다. 이 라이브러리들은 파이썬 패키지 인덱스(PyPI)에서 쉽게 설치할 수 있으며, 데이터 분석, 웹 개발, 머신러닝 등 다양한 분야에서 활용됩니다. 
- 예시: numpy, pandas, requests, scikit-learn 등이 있습니다.
- 라이브러리를 활용하면 복잡한 기능도 간단하게 구현할 수 있어, 개발의 효율성을 크게 높여줍니다.

# 1. Pandas 

## pandas 개괄
https://pandas.pydata.org/docs/user_guide/10min.html

- 판다스(Pandas)는 파이썬에서 데이터 분석과 조작을 위해 가장 널리 사용되는 라이브러리 중 하나입니다. 
- 주로 테이블 형식의 데이터(예: 엑셀 파일, CSV 파일 등)를 다루기 위해 사용되며, 대용량 데이터 처리에도 유용합니다.

## pandas의 주요 특징과 기능

- 1. 데이터 구조:
- DataFrame: 2차원 '행렬' 형식데이터 구조(표 형식)로, 엑셀의 시트와 비슷한 행(row)과 열(column)로 구성된 데이터 형태입니다. 데이터 분석에서 가장 많이 사용됩니다.
- Series: 1차원 벡터 형식데이터 구조로, 배열과 비슷하지만, 각 데이터에 인덱스를 가질 수 있습니다.
- 2.데이터 입출력:
- CSV, 엑셀, SQL, JSON 등 다양한 파일 형식으로부터 데이터를 읽고 쓸 수 있습니다.
- CSV : CSV(Comma Separated Value) 포맷 , CSV 파일 포맷은 데이터 값이 쉽표(comma)로 구분되는 텍스트 파일
- 3. 데이터 정제 및 처리:
- 결측값(NaN) 처리, 중복 데이터 제거, 데이터 정렬, 필터링, 변환 등 데이터를 정제하고 가공하는 다양한 기능을 제공합니다.
- 4. 데이터 연산 및 통계 분석:
- 데이터 그룹화(grouping), 합계(sum), 평균(mean), 분산(variance) 등의 통계적 연산을 손쉽게 수행할 수 있습니다.
- 5. 데이터 병합 및 결합:
- 여러 DataFrame을 하나로 합치거나 특정 조건에 따라 데이터를 결합할 수 있는 기능(merge, join 등)을 제공합니다.
- 6. 시간 데이터 처리:
- 시간과 날짜를 포함한 데이터를 효율적으로 처리하고 분석할 수 있는 기능을 지원합니다.
- 7. 시각화:
- 간단한 데이터 시각화 기능을 제공하며, 주로 matplotlib과 같은 시각화 라이브러리와 함께 사용됩니다.

## Pandas 자료구조 : Series와 DataFrame

- Pandas 자료구조
- 1) Series: 1차원 벡터 형식 , 하나의 열이 되는 데이터를 리스트나 일차원 배열을 준비한다.
- 2) DataFrame: 2차원 행렬 형식  행(row)과 열(column)로 구성
- 행(row) : 가로줄 ,  열(column) : 세로줄
- Panel: 3차원 배열 형식

### Series 이해

- Series :  1차원 형태의 자료구조
- 파이썬의 리스트(list)와 비슷하고 , 딕셔너리와 유사한 자료구조
- Series모든 데이터 유형(정수, 문자열, 부동 소수점 숫자, Python 객체 등)을 보유할 수 있는 1차원 레이블 배열
- Series형태의 자료구조는 기본적으로 index와 value 가 존재하기 때문에 일반적으로 생각하는 시계열 형태와 일치

### 시리즈 생성하기

In [156]:
# 라이브러리 불러오기

import pandas as pd

# 판다스로 시리즈 만들기
# 시리즈 인덱스를 따로 지정하지 않으면 0 부터 시작한다. 
# 인덱스를 따로 지정하려면 index 인자에 리스트를 전달하면 된다. 
# columns 인자를 사용하면 데이터프레임의 열 순서를 지정할 수 있다.
# 데이터생성하기
income_list = pd.Series([45652, 26392, 46405],
              index=["남성","남성","여성"])
income_list

남성    45652
남성    26392
여성    46405
dtype: int64

In [157]:
income_list1 = pd.Series([45652, 26392, 46405],index=["남성","여성","여성"])
income_list1

남성    45652
여성    26392
여성    46405
dtype: int64

In [158]:
income_list2 = pd.Series([100, 120, 80],index=["서울경찰청","경기경찰청","부산경찰청"])
income_list2

서울경찰청    100
경기경찰청    120
부산경찰청     80
dtype: int64

### 시리즈 구성 확인하기 

- 판다스 패키지의 시리즈 클래스는 dictionary와 비슷한 구조로 index와 values로 구성

In [159]:
# index 확인
print(income_list.index)

Index(['남성', '남성', '여성'], dtype='object')


In [160]:
# value 확인
print(income_list.values)

[45652 26392 46405]


### 시리즈 이름 지정하기

In [161]:
# 인덱스 이름 지정
# pd.Series()함수의 옵션으로 index명을 지정

income_list.index.name = "성별","총소득"
income_list

(성별, 총소득)
남성    45652
남성    26392
여성    46405
dtype: int64

In [162]:
income_list2.index.name = "경찰청","범죄발생건수"
income_list2

(경찰청, 범죄발생건수)
서울경찰청    100
경기경찰청    120
부산경찰청     80
dtype: int64

### Series를  DataFrame으로 변환 가능 

- DataFrame : 여러 개의 로우(row), 칼럼(Column)으로 구성된 2차원 형태의 자료구조
- row, Column, , Series들로 구성된 형태

In [163]:
# 변수.to-frame()
income_list.to_frame()

,0
"(성별, 총소득)",
남성,45652
남성,26392
여성,46405


In [164]:
df = pd.DataFrame(income_list)
df

,0
"(성별, 총소득)",
남성,45652
남성,26392
여성,46405


### 시리즈의 기초 통계 메서드 사용하기 

- describe                요약 통계량 계산
- min                     최솟값 반환
- max                     최댓값 반환
- mean                    산술 평균 반환
- median                  중간값 반환
- std                     표준편차

In [165]:
print(income_list.describe())

count        3.000000
mean     39483.000000
std      11343.388515
min      26392.000000
25%      36022.000000
50%      45652.000000
75%      46028.500000
max      46405.000000
dtype: float64


In [166]:
statistics = income_list.describe()

print(statistics)

count        3.000000
mean     39483.000000
std      11343.388515
min      26392.000000
25%      36022.000000
50%      45652.000000
75%      46028.500000
max      46405.000000
dtype: float64


In [167]:
print(income_list.mean())

39483.0


In [168]:
print(income_list.std())

11343.388514901533


In [169]:
import pandas as pd
abc = pd.Series([600, 590, 570, 550, 570])

In [170]:
print(abc.describe())

count      5.000000
mean     576.000000
std       19.493589
min      550.000000
25%      570.000000
50%      570.000000
75%      590.000000
max      600.000000
dtype: float64


In [171]:
df2 = pd.DataFrame([abc])
print (df2)

     0    1    2    3    4
0  600  590  570  550  570


In [172]:
# # 유용한 메소드
# append                  2개 이상의 시리즈 연결
# drop_duplicates         중복값이 없는 시리즈 반환
# equals                  시리즈에 해당 값을 가진 요소가 있는지 확인
# get_values              시리즈 값 구하기(values 속성과 동일)
# isin                    시리즈에 포함된 값이 있는지 확인

# replace                 특정 값을 가진 시리즈 값을 교체
# sample                  시리즈에서 임의의 값을 반환
# sort_values             값을 정렬
# to_frame                시리즈를 데이터프레임으로 변환

## DataFrame 생성하기

### 기본 방법 3가지 ( 수집된 데이터가 엑셀등의 자료가 아닌 경우)

In [173]:
# 첫번째 방법
# 2차원 표에서 column 단위로 데이터를 표현하여 dataframe 생성
# ==> column명을 딕셔너리의 key로 (아래에서 crime) ,  데이터는 딕셔너리의 value로

In [174]:
from pandas import DataFrame

crime={"살인":[10,5,20], "강도":[55,65,40], "절도":[150,200,350]}

police =["서울경찰청", "부산경찰청", "인천경찰청"]

df=DataFrame(crime, police)
print(df)

       살인  강도   절도
서울경찰청  10  55  150
부산경찰청   5  65  200
인천경찰청  20  40  350


In [175]:
# 두번째 방법
# 2차원 표에서 row 단위로 데이터를 리스트로 표현하여 dataframe 생성
# data에 해당하는 아래 crime, index에 해당하는 police , columns 을 모두 리스트로 표현하여 생성하는 방법

In [176]:
from pandas import DataFrame

crime=[[10,55,150], [5,65,200], [20,40,350]]

police =["서울경찰청", "부산경찰청", "인천경찰청"]
columns=["살인","강도","절도"]

df=DataFrame(data=crime, index=police,columns=columns)
print(df)

       살인  강도   절도
서울경찰청  10  55  150
부산경찰청   5  65  200
인천경찰청  20  40  350


In [177]:
# 세번째 방법
# 2차원 표에서 row 단위로 데이터를 딕셔너리로 표현하여 dataframe 생성

In [178]:
from pandas import DataFrame

crime=[{"살인":10, "강도":55, "절도":150},
       {"살인":5, "강도":65, "절도":200},
       {"살인":20, "강도":40, "절도":350}]

police =["서울경찰청", "부산경찰청", "인천경찰청"]

df=DataFrame(data= crime, index=police)
print(df)

       살인  강도   절도
서울경찰청  10  55  150
부산경찰청   5  65  200
인천경찰청  20  40  350


In [179]:
df.describe()

,살인,강도,절도
count,3.000000,3.000000,3.000000
mean,11.666667,53.333333,233.333333
std,7.637626,12.583057,104.083300
min,5.000000,40.000000,150.000000
25%,7.500000,47.500000,175.000000
50%,10.000000,55.000000,200.000000
75%,15.000000,60.000000,275.000000
max,20.000000,65.000000,350.000000


In [180]:
print(df)

       살인  강도   절도
서울경찰청  10  55  150
부산경찰청   5  65  200
인천경찰청  20  40  350


###  List를 바탕으로 한번 DataFrame을 생성

In [181]:
#### 1) List를 바탕으로 한번 DataFrame을 생성

 
import pandas as pd
 
data = [['Choi',22],['Kim',40],['Joo',15],['Baek',18]]
 
df = pd.DataFrame(data,columns=['Name','age'])
 
print(df)

   Name  age
0  Choi   22
1   Kim   40
2   Joo   15
3  Baek   18


### Dictionary를 바탕으로 한번 DataFrame을 생성

In [182]:
# DataFrame 생성하기

# Dictionary를 바탕으로 한번 DataFrame을 생성

# 딕셔너리(dict)를 통해 각 칼럼에 대한 데이터를 저장한 후
# 딕셔너리를 DataFrame 클래스의 생성자 인자로 넘겨주면 DataFrame 객체 생성     

In [183]:
from datetime import datetime, timedelta
import pandas as pd
import random

# 랜덤 시드 설정
random.seed(42)

# 데이터 개수 설정
data_count = 100

# 날짜 범위 설정
start_date = datetime(2022, 1, 1)
end_date = datetime(2022, 12, 31)
date_range = [start_date + timedelta(days=random.randint(0, (end_date - start_date).days)) for _ in range(100)]

# ID, 나이, 성별, 소득, 범죄건수 랜덤 생성
id_list = [i+1 for i in range(data_count)]
age_list = [random.randint(18, 80) for _ in range(data_count)]
gender_list = ['남성', '여성']
gender = [random.choice(gender_list) for _ in range(data_count)]
income_list = [random.randint(20000, 150000) for _ in range(data_count)]
crime_count_list = [random.randint(0, 10) for _ in range(data_count)]

# 데이터프레임 생성
data = {
    
    '날짜': date_range,
    'ID' : id_list,
    '나이': age_list,
    '성별': gender,
    '소득': income_list,
    '범죄건수': crime_count_list
}

df = pd.DataFrame(data)

df



,날짜,ID,나이,성별,소득,범죄건수
0,2022-11-24,1,71,여성,141440,5
1,2022-02-27,2,67,남성,122769,4
2,2022-01-13,3,67,남성,122908,2
3,2022-05-21,4,21,여성,79638,7
4,2022-05-06,5,32,남성,57388,8
...,...,...,...,...,...,...
95,2022-12-19,96,29,남성,65745,5
96,2022-10-13,97,50,여성,135456,4
97,2022-04-23,98,76,남성,29016,3
98,2022-12-17,99,24,여성,135247,3


In [184]:
# index 날짜로 변경 set_index()
df.set_index("날짜",inplace=True)

### DataFrame 로우(인덱스) ,칼럼 선택

In [185]:
#'칼럼에 대한 데이터만 DataFrame 객체로부터 얻는 경우
age = df['나이']
print(age)
    

날짜
2022-11-24    71
2022-02-27    67
2022-01-13    67
2022-05-21    21
2022-05-06    32
              ..
2022-12-19    29
2022-10-13    50
2022-04-23    76
2022-12-17    24
2022-06-16    73
Name: 나이, Length: 100, dtype: int64


In [186]:
# DataFrame 객체의 로우에 접근하려면 loc 메서드를 사용해 인덱스 값을 넘겨주어야 함.
id_data = df.loc["2022-02-27"]
print(id_data)
print(type(id_data))

ID           2
나이          67
성별          남성
소득      122769
범죄건수         4
Name: 2022-02-27 00:00:00, dtype: object
<class 'pandas.core.series.Series'>


In [187]:
# DataFrame 객체의 칼럼 이름과 인덱스 값을 확인하려면 각각 columns와 index 속성을 사용
print(df.columns)
print(df.index)

Index(['ID', '나이', '성별', '소득', '범죄건수'], dtype='object')
DatetimeIndex(['2022-11-24', '2022-02-27', '2022-01-13', '2022-05-21',
               '2022-05-06', '2022-04-25', '2022-03-13', '2022-02-22',
               '2022-12-13', '2022-10-07', '2022-02-14', '2022-10-30',
               '2022-08-05', '2022-01-17', '2022-01-16', '2022-02-17',
               '2022-04-22', '2022-04-30', '2022-09-16', '2022-11-05',
               '2022-01-14', '2022-10-15', '2022-04-12', '2022-11-29',
               '2022-12-26', '2022-10-07', '2022-08-03', '2022-04-23',
               '2022-08-18', '2022-10-29', '2022-05-23', '2022-01-04',
               '2022-03-23', '2022-12-24', '2022-08-05', '2022-06-24',
               '2022-05-23', '2022-03-21', '2022-04-21', '2022-06-22',
               '2022-02-22', '2022-02-17', '2022-07-14', '2022-02-19',
               '2022-07-03', '2022-06-26', '2022-11-06', '2022-05-16',
               '2022-01-23', '2022-08-24', '2022-10-02', '2022-03-05',
               '2022-

### 데이터프레임에 대한 기초 통계량 확인

In [188]:
# 데이터프레임에 대한 기초 통계량 확인

df.describe()

,ID,나이,소득,범죄건수
count,100.000000,100.000000,100.000000,100.000000
mean,50.500000,49.790000,82376.280000,4.540000
std,29.011492,18.325505,37949.175375,3.150822
min,1.000000,18.000000,21220.000000,0.000000
25%,25.750000,34.000000,50254.500000,2.000000
50%,50.500000,50.000000,86108.000000,4.000000
75%,75.250000,66.000000,111945.250000,7.000000
max,100.000000,80.000000,146970.000000,10.000000


## 파이썬을 이용해서 외부 데이터 읽어오기 

## CSV(Comma Separated Value) 파일 불러오기

In [189]:
#  CSV(Comma Separated Value) 포맷 입출력
#  --> CSV 파일 포맷은 데이터 값이 쉽표(comma)로 구분되는 텍스트 파일이다.
# CSV 파일 입력¶
# CSV 파일로부터 데이터를 읽어 데이터프레임을 만들 때는 pandas.read_csv 함수를 사용한다. 
# 함수의 입력값으로 파일 이름을 넣는다.

In [190]:
import pandas as pd
data=pd.read_csv("crime_list.csv")

In [191]:
data

,날짜,ID,나이,성별,소득,범죄건수
0,2022-11-24,1,71,여성,141440,5
1,2022-02-27,2,67,남성,122769,4
2,2022-01-13,3,67,남성,122908,2
3,2022-05-21,4,21,여성,79638,7
4,2022-05-06,5,32,남성,57388,8
...,...,...,...,...,...,...
95,2022-12-19,96,29,남성,65745,5
96,2022-10-13,97,50,여성,135456,4
97,2022-04-23,98,76,남성,29016,3
98,2022-12-17,99,24,여성,135247,3


##  csv 파일 불러오기 

In [192]:
# csv 파일 불러오기 
pd.read_csv('crime_list.csv')

,날짜,ID,나이,성별,소득,범죄건수
0,2022-11-24,1,71,여성,141440,5
1,2022-02-27,2,67,남성,122769,4
2,2022-01-13,3,67,남성,122908,2
3,2022-05-21,4,21,여성,79638,7
4,2022-05-06,5,32,남성,57388,8
...,...,...,...,...,...,...
95,2022-12-19,96,29,남성,65745,5
96,2022-10-13,97,50,여성,135456,4
97,2022-04-23,98,76,남성,29016,3
98,2022-12-17,99,24,여성,135247,3


## 데이터 전처리

### 결측 데이터를 삭제하는 방법

In [193]:
import pandas as pd

df=pd.read_csv("crime_list.csv")

In [194]:
df

,날짜,ID,나이,성별,소득,범죄건수
0,2022-11-24,1,71,여성,141440,5
1,2022-02-27,2,67,남성,122769,4
2,2022-01-13,3,67,남성,122908,2
3,2022-05-21,4,21,여성,79638,7
4,2022-05-06,5,32,남성,57388,8
...,...,...,...,...,...,...
95,2022-12-19,96,29,남성,65745,5
96,2022-10-13,97,50,여성,135456,4
97,2022-04-23,98,76,남성,29016,3
98,2022-12-17,99,24,여성,135247,3


In [195]:
df.isnull().sum()[df.isnull().sum() > 0]


Series([], dtype: int64)

In [196]:
# 소득 컬럼에서 결측지 삭제(dropna) 하고 새로운 data --> data11로 저장
# na : not avaliable 
df1=df.dropna(subset=['소득'])
df1

,날짜,ID,나이,성별,소득,범죄건수
0,2022-11-24,1,71,여성,141440,5
1,2022-02-27,2,67,남성,122769,4
2,2022-01-13,3,67,남성,122908,2
3,2022-05-21,4,21,여성,79638,7
4,2022-05-06,5,32,남성,57388,8
...,...,...,...,...,...,...
95,2022-12-19,96,29,남성,65745,5
96,2022-10-13,97,50,여성,135456,4
97,2022-04-23,98,76,남성,29016,3
98,2022-12-17,99,24,여성,135247,3


In [197]:
# 소득 컬럼, 범죄건수 에서 결측지 삭제하고 새로운 data --> data11로 저장
df2=df.dropna(subset=['소득', '범죄건수'])
df2 

,날짜,ID,나이,성별,소득,범죄건수
0,2022-11-24,1,71,여성,141440,5
1,2022-02-27,2,67,남성,122769,4
2,2022-01-13,3,67,남성,122908,2
3,2022-05-21,4,21,여성,79638,7
4,2022-05-06,5,32,남성,57388,8
...,...,...,...,...,...,...
95,2022-12-19,96,29,남성,65745,5
96,2022-10-13,97,50,여성,135456,4
97,2022-04-23,98,76,남성,29016,3
98,2022-12-17,99,24,여성,135247,3


In [198]:
# 모든 결측치가 있는 것을 지우는 경우

df3=df.dropna(axis=0)
df3

,날짜,ID,나이,성별,소득,범죄건수
0,2022-11-24,1,71,여성,141440,5
1,2022-02-27,2,67,남성,122769,4
2,2022-01-13,3,67,남성,122908,2
3,2022-05-21,4,21,여성,79638,7
4,2022-05-06,5,32,남성,57388,8
...,...,...,...,...,...,...
95,2022-12-19,96,29,남성,65745,5
96,2022-10-13,97,50,여성,135456,4
97,2022-04-23,98,76,남성,29016,3
98,2022-12-17,99,24,여성,135247,3


## 새롭게 저장하기

In [199]:
import pandas as pd

df3.to_csv('df3.csv',index = False) 

## 다시 불러오기

In [200]:
import pandas as pd
df3=pd.read_csv("df3.csv")

In [201]:
df3

,날짜,ID,나이,성별,소득,범죄건수
0,2022-11-24,1,71,여성,141440,5
1,2022-02-27,2,67,남성,122769,4
2,2022-01-13,3,67,남성,122908,2
3,2022-05-21,4,21,여성,79638,7
4,2022-05-06,5,32,남성,57388,8
...,...,...,...,...,...,...
95,2022-12-19,96,29,남성,65745,5
96,2022-10-13,97,50,여성,135456,4
97,2022-04-23,98,76,남성,29016,3
98,2022-12-17,99,24,여성,135247,3


# NumPy

- NumPy : Numerical Python
- 다차원(n차원 배열 생성 : 1차원, 2차원..) 배열(array) 연산기능을 모아둔 패키지
- 다차원 배열 객체와 이를 효율적으로 다루기 위한 다양한 함수들을 제공합니다. 
- 넘파이는 빠르고 유연한 배열 연산을 통해 수학, 과학, 공학 계산 등에 많이 사용되며, 다른 데이터 분석 및 머신러닝 라이브러리(예: Pandas, SciPy, Scikit-learn 등)의 기반이 되기도 합니다.
- 벡터, 행렬, 다차원 배열을 위한 파이썬 객체 및 이 객체들을 이용한 수치연산, 통계 계산 등의 기능
- 행렬, 배열의 수학연산을 벡터연산(일종의 병렬 연산)을 하여 성능을 개선 (연산속도 측면)

## http://www.numpy.org/

## 넘파이의 주요 특징과 기능

- 1. N차원 배열 객체 (ndarray):
- 넘파이의 핵심 데이터 구조로, 동일한 데이터 타입의 값들이 담긴 다차원 배열입니다. 
- 리스트와 유사하지만, 배열 크기가 고정되어 있고, 수치 계산에 훨씬 효율적입니다.
- 2. 빠른 연산 속도:
- 넘파이는 C 언어로 구현되어 있어 파이썬의 기본 리스트보다 훨씬 빠르게 수학적 연산을 수행할 수 있습니다.
- 3. 벡터화 연산:
- 반복문 없이 배열 전체에 대한 연산을 한 번에 수행할 수 있습니다. 
- 이를 통해 코드가 간결해지고 연산 속도가 빨라집니다.
- 4. 브로드캐스팅(Broadcasting):
- 크기가 다른 배열 간의 연산을 자동으로 맞춰 수행할 수 있습니다. 
- 예를 들어, 배열과 스칼라 값 간의 연산에서 배열의 각 요소에 스칼라 값이 적용됩니다.
- 5. 다양한 수학 함수:
- 선형대수, 통계, 푸리에 변환 등의 다양한 수학 함수들을 제공합니다.
- 6. 난수 생성:
- 다양한 분포에서 난수를 생성할 수 있어, 시뮬레이션이나 머신러닝에서 많이 활용됩니다.
- 7.파일 입출력:
- 배열 데이터를 바이너리 형식이나 텍스트 형식(CSV, TSV 등)으로 저장하거나 불러올 수 있습니다.

## 배열(array) 
1. 배열이란?
2. 배열 만들기
3. 배열 탐색하기
4. 배열 연산하기
5. 배열의 변환 

### 배열이란?

In [202]:
# 데이터 처리를 효율적으로 하기 위한 자료구조
# 배열 안에는 숫자나 문자열  모두를 담을 수 있다. 단, 배열 안에서는 동일 종류의 데이터만 담을 수 있다.
# - 리스트는 다른 유형의 데이터를 담을 수 있지만 배열은 불가
# 리스트 : [1,2,3] , [안산, 대학교, 경찰], [1,2, 안산, 4]
# 배열 : ([1,2,3]) , ([안산, 대학교, 경찰])

In [203]:
# 배열의 종류(차원: Dimension ) : 1차원, 2차원, 3차원
# n차원의 배열 (ndarray)
# 1) 1차원 배열 : 범죄건수 ([61000,59000,56500]) -->  리스트와 유사하나 , 연산 방법의 차이로 속도가 빠르다.
# 2) 2차원 배열 : 서울범죄건수, 부산범죄건수, ( [61000,59000,56500], [ 200000, 210000, 2250000])
# 3) 3차원 배열 : 2차원 배열이 수개 모여 있는 형태 

### 배열 만들기

- 배열을 만들기 위한 함수
- 1) np.array  : 초기 값을 지정하여 배열 만들기
- 2) np.arrange : 순차적인 숫자 이용 배열 만들기
- 3) np. rand : 랜덤하게 숫자 배열 만들기

In [204]:
### np.array

In [205]:
# 만드는 방법
# np.array ([나열된 데이터 객체])

In [206]:
# 넘파이 불러오기
import numpy as np
# np.array ([나열된 데이터 객체])
# stock1 리스트 데이터를 배열 형태로 변환

person=[15000, 14500, 16000, 17000]
arr1=np.array([person])
arr1

array([[15000, 14500, 16000, 17000]])

In [207]:
# 데이터 타입(형식) 확인하기

type(arr1)

numpy.ndarray

In [208]:
### np.arange 

- 기본 내장함수 range 와 유사함 : 연속된 숫자로 배열 만들기
- 코드 방법 :  np.arrange([])

In [209]:
import numpy as np
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [210]:
# np.arange(시작번호, 끝번호)
np.arange(2, 10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [132]:
# np.arange(시작번호, 끝번호, 건너뛰는 수)
np.arange(1, 30, 7)

array([ 1,  8, 15, 22, 29])

### 배열 탐색하기

- 배열의 타입을 확인하는 경우
- shape : 배열 형태 확인하는 경우
- dtype : 배열 데이터 타입 확인하는 경우
- astype : 배열의 데이터 타입 변경하기
- 인덱스 범위 지정 : 배열 안 데이터 일부 만 보는 경우

2.3.1. shape : 배열 형태 확인하는 경우¶

In [133]:
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [134]:
# arr 에 대하여 배열 형태 확인하는 경우
arr.shape
# 결과 10개 값인 1차원 배열

(10,)

### 배열 연산하기

In [135]:
arr=np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [136]:
# 배열에 사칙연산

In [137]:
arr+10

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [138]:
arr-1

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [139]:
arr*10

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [140]:
# 배열간 더하기
# 주의 : 배열 수가 일치해야 함

In [141]:
arr=np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [142]:
arr1=np.arange(20,29)
arr1

array([20, 21, 22, 23, 24, 25, 26, 27, 28])

In [143]:
arr+arr1

array([21, 23, 25, 27, 29, 31, 33, 35, 37])

In [144]:
# 제곱
np.square(arr)

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [145]:
# 제곱근
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        ])

In [146]:
# 배열 합하기
np.add(arr, arr1)

array([21, 23, 25, 27, 29, 31, 33, 35, 37])

In [147]:
# 배열 합
np.sum(arr)

45

2.5. 배열 기초 통계량

In [148]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [149]:
# 평균
np.mean(arr)

5.0

In [150]:
# 표준편차
np.std(arr)

2.581988897471611

In [151]:
# 최대
np.max(arr)

9

In [152]:
# 최소
np.min(arr)

1