# 데이터분석을 위한 파이썬 기초(시작)

# python 설치
### (http://www.python.org/downloads)

In [2]:
# 1. 홈페이지의 다운로드 페이지(http://www.python.org/downloads)에서 윈도우용 파이썬 언어 패키지를 다운로드
# 2. 인스톨러를 실행 --> "Install Now"를 선택 -->  설치 진행
# 파이썬이 어느 곳에서든지 실행될 수 있도록 "Add Python3.8 to PATH" 옵션 반드시 선택
# 3. 설치가 완료 : [close]를 클릭 종료

# jupyter notebook 설치

In [ ]:
# cmd 창을 열고 명령어를 이용해서 설치
# pip install jupyter

In [ ]:
# jupyter notebook 실행¶
# C:\Users\user>cd 
# C:\apps>cd finace_data
# C:\apps\finace_data>jupyter notebook

## 아나콘다(Anaconda) 설치
### https://www.anaconda.com/products/distribution

In [ ]:
# 아나콘다는 데이터 사이언스에 필요한 여러가지 패키지를 묶어 놓은 것
# 파이썬 배포판

In [ ]:
# 윈도우 또는 mac
# 64비트, 32비트 
# 확인 : 설정 - 시스템 - 정보 : 64비트 운영 체제, x64 기반 프로세
# Advanced Options나오면 둘 다 체크

### 실행하기

In [ ]:
# 1. 아나콘다 네비게이터(Anaconda Navigator) 실행
# CMD Prompt 실행(Launch)
# Jupyter notebook 실행

In [ ]:
# 3. 윈도우 : 아나콘다 프롬프트에서 실행  , 맥 : 터미널에서 

In [ ]:
# 2. (CMD Prompt)에서  Jupyter notebook을 실행

## 비주얼 스튜디오 코드(Visual Studio Code)를 설치
### https://code.visualstudio.com/download

In [ ]:
# 1. 비주얼 스튜디오 코드 다운로드 페이지 접속
# 2. 비주얼 스튜디오 코드 다운로드
# 3. Install 파일 실행
# 4. 비주얼 스튜디오 코드 실행 및 마무리

In [ ]:
#1. 비주얼 스튜디오 코드 다운로드 페이지 접속
#  https://code.visualstudio.com/download

In [ ]:
# 2. 비주얼 스튜디오 코드 다운로드
# 비주얼 스튜디오 코드 다운로드 페이지로 들어가서 내 컴퓨터 OS에 따라 설치 가능

In [ ]:
# 3. Install 파일 실행

# 파이썬 자습서
## https://docs.python.org/ko/3/tutorial/

# 파이썬 기초

# 1. print 하기

In [1]:
# 문자열을 출력 : 따옴표 필요--> 큰따옴표, 작은따옴표 모두 가능
print('Hello Python!')

Hello Python!


In [31]:
print("안산대학교")

안산대학교


In [3]:
# 숫자를 출력
print(1)

1


In [5]:
print(123)  

123


In [6]:
print([1, 2, 3])

[1, 2, 3]


# 2. input

In [7]:
name = input('What is your name?')

What is your name?jyb


# 3. 기본 함수 만들어보기

In [8]:
# def : definition
# 함수의 경우 들여쓰기(4칸)
def add(a, b):
    x=a+b
    return x
y= add(2,3)
print(y)

5


In [9]:
2+3

5

# 라이브러리 보기/설치

In [ ]:
# 라이브러리가 필요한 사례보기 ?

In [10]:
100*2

200

In [11]:
log(10)

NameError: name 'log' is not defined

In [12]:
# math 모듈(Math Module)
# 복잡한 연산이 필요한 경우 math 모듈을 사용
import math
math.log(10)

2.302585092994046

In [13]:
# 스타임포트 방식(한꺼번에 임포트함. 이름공간과 관련된 모호성 문제)
# from 모듈명 import 뒤에 * 을 입력 : 그 모듈에 내포된 모든 함수를 로드하여 별다른 수식 없이 함수를 모두 사용 가능
from math import *  

In [14]:
log(10)

2.302585092994046

# 설치되어 있는 라이브러리 보기

In [16]:
pip list

Package                 Version
----------------------- -------------------
absl-py                 0.13.0
ansi2html               1.6.0
appdirs                 1.4.4
arelle                  2.2
argon2-cffi             20.1.0
astor                   0.8.1
astunparse              1.6.3
async-generator         1.10
atomicwrites            1.4.0
attrs                   21.2.0
Note: you may need to restart the kernel to use updated packages.backcall                0.2.0
Backtesting             0.3.2
backtrader              1.9.76.123
beautifulsoup4          4.9.3
bleach                  3.3.0
bokeh                   2.4.2
Brotli                  1.0.9

bs4                     0.0.1
bt                      0.2.9
cachetools              4.2.2
certifi                 2021.5.30
cffi                    1.14.6
chardet                 4.0.0


charset-normalizer      2.0.1
chart-studio            1.1.0
click                   8.0.1
colorama                0.4.4
convertdate             2.3.2
cssselect               1.1.0
cycler                  0.10.0
Cython                  0.29.24
dart-fss                0.3.17
dash                    1.21.0
dash-core-components    1.17.1
dash-html-components    1.1.4
dash-table              4.12.0
datapungi_fed           0.3.1
DateTime                4.3
debugpy                 1.3.0
decorator               5.0.9
defusedxml              0.7.1
Deprecated              1.2.12
empyrical               0.5.5
entrypoints             0.3
ephem                   4.0.0.2
et-xmlfile              1.1.0
fake-useragent          0.1.11
feedparser              6.0.8
ffn                     0.3.6
finance-datareader      0.9.31
Flask                   2.0.1
Flask-Compress          1.10.1
flatbuffers             1.12
formulaic               0.2.4
fredapi                 0.4.3
fsspec                  2021.8.1

# 라이브러리 설치

In [ ]:
pip install pandas

# 라이브러리 불러오기

In [ ]:
# import 방법 :  import 모듈명
import numpy

In [ ]:
# 모듈을 로드 한 뒤 함수명만을 사용하여 함수를 사용
#  from 모듈명 import 함수명 
import math from add

In [ ]:
# 별칭 (alias) 를 as로 지정하여 간편하게 불러오는 방법

In [21]:
import numpy as np   

In [22]:
# import된 라이브러리(패키지) 내용을 살펴보는 경우 

dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__file__',
 '__getattr__',
 '__git_revision__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_

In [ ]:
# 라이브러리에 포함된 함수 사용하기

In [ ]:
# numpy 모듈의 arange 함수
#  [start, stop) 에서 step 의 크기만큼 일정하게 떨어져 있는 숫자들을 array 형태로 반환해 주는 함수
# stop 매개변수의 값은 반드시 전달되어야 함.
# start 는 step 은 꼭 전달되지 않아도 된다. 
# start 값이 전달되지 않으면 0 을 기본값으로 가진다.

In [23]:
# import numpy as np :  numpy 모듈을 np 라는 별칭으로 import  하겠다는 의미

import numpy as np

# np.arange(5) 의 경우 stop 매개변수의 값만 전달되었으므로 [0, 5) 
np.arange(5)

array([0, 1, 2, 3, 4])

In [25]:
# np.arange(5.0) 의 경우 
# 전달된 stop 매개변수의 값 0.으로 부터 정수가 아닌 실수값임을 추론

np.arange(5.0)



array([0., 1., 2., 3., 4.])

In [27]:
# np.arange(2, 6) 의 경우 
# start=2, stop=6 이 주어진 경우
# [2, 6) 에서 2를 시작으로 1 간격으로 떨어진 수들을 array의 형태로 반환

np.arange(2,6)

array([2, 3, 4, 5])

In [30]:
# np.arange(2, 5, 2) 의 경우 
# start=2, stop=5, step=2 
# [2, 5) 에서 2을 시작으로 2 간격으로 떨어진 수들을 array의 형태로 반환

np.arange(2,5,2)

array([2, 4])

In [ ]:
# dtype 의 경우 결과로 반환되는 array 이의 type 을 지정할 때 사용
# dtype 값이 주어지지 않는 경우 전달된 다른 매개 변수로부터 type 을 추론하게 된다.

# 키워드(Keyword, 예약어)

In [ ]:
import keyword
print(keyword.kwlist)

# 사칙연산 연산자 사례

In [ ]:
# +, - , * , /

In [32]:
1+2

3

In [33]:
print(1 + 2)  # 계산결과를 출력합니다.

3


In [34]:
5-3

2

In [35]:
1+2
5-3

2

In [36]:
5*3

15

In [37]:
6/3

2.0

In [38]:
5**2

25

In [39]:
7/2

3.5

In [40]:
# //  : 나눗셈에서 몫만 
7//2

3

In [42]:
# % : 나누기 연산 후 몫이 아닌 나머지를 구함
7%2

1

In [ ]:
#파이썬에서도 일반 수학의 연산 순서를 따른다. 
#곱셈과 나눗셈이 덧셈이나 뺄셈보다 먼저 연산

In [43]:
2+3*2

8

In [44]:
10+6/2

13.0

In [ ]:
# 괄호가 있으면 괄호안을 먼저 계산한다. 

In [45]:
10-(3*3-1)

2

In [ ]:
##부등식의 참과 거짓 계산¶True, False
## 파이썬은 참과 거짓을 계산하는 부등식 연산도 가능

In [ ]:
# 부등호 기호 : >  , <  

In [51]:
3 > 1

True

In [48]:
3 < 1

False

In [47]:
1 > 2

False

In [ ]:
# 등호 기호 :  ==

In [50]:
2 == 2

True

In [ ]:
# 같지 않다. !=

In [52]:
2 != 2 

False

In [53]:
2 != 3 

True

In [54]:
#2는 3보다 작거나 같다
2 <= 3

True

In [56]:
#2는 3보다 크거나 같다
2>=3

False

# 변수(variable) 할당하여 연산하기

In [ ]:
# 변수명을 할당(지정)하여 사용하면 편리

In [57]:
a=3
b=5
a+b

8

In [58]:
print(b-a)

2


In [59]:
print( a - b )

-2


In [60]:
print(a/b)

0.6


In [61]:
b**10

9765625