NumPy

# 개괄 이해

- NumPy : Numerical Python
- 다차원(n차원 배열 생성 : 1차원, 2차원..) 배열(array) 연산기능을 모아둔 패키지
- 다차원 배열 객체와 이를 효율적으로 다루기 위한 다양한 함수들을 제공합니다. 
- 넘파이는 빠르고 유연한 배열 연산을 통해 수학, 과학, 공학 계산 등에 많이 사용되며, 다른 데이터 분석 및 머신러닝 라이브러리(예: Pandas, SciPy, Scikit-learn 등)의 기반이 되기도 합니다.
- 벡터, 행렬, 다차원 배열을 위한 파이썬 객체 및 이 객체들을 이용한 수치연산, 통계 계산 등의 기능
- 행렬, 배열의 수학연산을 벡터연산(일종의 병렬 연산)을 하여 성능을 개선 (연산속도 측면)

## http://www.numpy.org/

## 넘파이의 주요 특징과 기능

- 1. N차원 배열 객체 (ndarray):
- 넘파이의 핵심 데이터 구조로, 동일한 데이터 타입의 값들이 담긴 다차원 배열입니다. 
- 리스트와 유사하지만, 배열 크기가 고정되어 있고, 수치 계산에 훨씬 효율적입니다.
- 2. 빠른 연산 속도:
- 넘파이는 C 언어로 구현되어 있어 파이썬의 기본 리스트보다 훨씬 빠르게 수학적 연산을 수행할 수 있습니다.
- 3. 벡터화 연산:
- 반복문 없이 배열 전체에 대한 연산을 한 번에 수행할 수 있습니다. 
- 이를 통해 코드가 간결해지고 연산 속도가 빨라집니다.
- 4. 브로드캐스팅(Broadcasting):
- 크기가 다른 배열 간의 연산을 자동으로 맞춰 수행할 수 있습니다. 
- 예를 들어, 배열과 스칼라 값 간의 연산에서 배열의 각 요소에 스칼라 값이 적용됩니다.
- 5. 다양한 수학 함수:
- 선형대수, 통계, 푸리에 변환 등의 다양한 수학 함수들을 제공합니다.
- 6. 난수 생성:
- 다양한 분포에서 난수를 생성할 수 있어, 시뮬레이션이나 머신러닝에서 많이 활용됩니다.
- 7.파일 입출력:
- 배열 데이터를 바이너리 형식이나 텍스트 형식(CSV, TSV 등)으로 저장하거나 불러올 수 있습니다.

# 배열(array) 
1. 배열이란?
2. 배열 만들기
3. 배열 탐색하기
4. 배열 연산하기
5. 배열의 변환 

## 배열이란?

In [2]:
# 데이터 처리를 효율적으로 하기 위한 자료구조
# 배열 안에는 숫자나 문자열  모두를 담을 수 있다. 단, 배열 안에서는 동일 종류의 데이터만 담을 수 있다.
# - 리스트는 다른 유형의 데이터를 담을 수 있지만 배열은 불가
# 리스트 : [1,2,3] , [안산, 대학교, 경찰], [1,2, 안산, 4]
# 배열 : ([1,2,3]) , ([안산, 대학교, 경찰])

In [3]:
# 배열의 종류(차원: Dimension ) : 1차원, 2차원, 3차원
# n차원의 배열 (ndarray)
# 1) 1차원 배열 : 범죄건수 ([61000,59000,56500]) -->  리스트와 유사하나 , 연산 방법의 차이로 속도가 빠르다.
# 2) 2차원 배열 : 서울범죄건수, 부산범죄건수, ( [61000,59000,56500], [ 200000, 210000, 2250000])
# 3) 3차원 배열 : 2차원 배열이 수개 모여 있는 형태 

## 배열 만들기 

- 배열을 만들기 위한 함수
- 1) np.array  : 초기 값을 지정하여 배열 만들기
- 2) np.arrange : 순차적인 숫자 이용 배열 만들기
- 3) np. rand : 랜덤하게 숫자 배열 만들기

### np.array

In [3]:
# 만드는 방법
# np.array ([나열된 데이터 객체])

In [4]:
# 넘파이 불러오기
import numpy as np
# np.array ([나열된 데이터 객체])
# stock1 리스트 데이터를 배열 형태로 변환

person=[15000, 14500, 16000, 17000]
arr1=np.array([person])
arr1

array([[15000, 14500, 16000, 17000]])

In [6]:
# 데이터 타입(형식) 확인하기

type(arr1)

numpy.ndarray

### np.arange 

- 기본 내장함수 range 와 유사함 : 연속된 숫자로 배열 만들기
- 코드 방법 :  np.arrange([])

In [7]:
import numpy as np
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
# np.arange(시작번호, 끝번호)
np.arange(1, 9)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [9]:
# np.arange(시작번호, 끝번호, 건너뛰는 수)
np.arange(1, 30, 2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

## 배열 탐색하기

- 배열의 타입을 확인하는 경우
- shape : 배열 형태 확인하는 경우
- dtype : 배열 데이터 타입 확인하는 경우
- astype : 배열의 데이터 타입 변경하기
- 인덱스 범위 지정 : 배열 안 데이터 일부 만 보는 경우

### shape : 배열 형태 확인하는 경우

In [10]:
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
# arr 에 대하여 배열 형태 확인하는 경우
arr.shape
# 결과 10개 값인 1차원 배열

(10,)

### dtype : 배열 데이터 타입 확인하는 경우 

In [12]:
# arr 에 대하여 배열에 포함된 데이터 타입 확인하는 경우
arr.dtype
# 결과 정수 값으로 이루어 짐.


dtype('int64')

### astype : 배열의 데이터 타입 변경하기

In [13]:
# 문자형으로 데이터 타입을 변경하는 경우
arr1=arr.astype(str)
# 문자형으로 변경됨 : '' 안에 숫자가 있다.
arr1

array(['0', '1', '2', '3', '4', '5', '6', '7', '8', '9'], dtype='<U21')

### 인덱스 범위 지정

In [14]:
# 인덱스 범위 지정 : 배열 안 데이터 일부 만 보는 경우

In [15]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
# 4부터 7번 (-1) 까지
arr[4:7]

array([4, 5, 6])

In [17]:
# 값을 할당하기
# 인덱스 2 에 20을 할당
arr[2]=20
arr

array([ 0,  1, 20,  3,  4,  5,  6,  7,  8,  9])

## 배열 연산하기

In [18]:
arr=np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
# 배열에 사칙연산

In [20]:
arr+10

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [21]:
arr-1

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [22]:
arr*10

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [23]:
# 리스트와 비교

In [24]:
list= [1, 2, 3, 4, 5, 6, 7, 8, 9]
list

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [25]:
list*10

[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9]

In [26]:
# 배열간 더하기
# 주의 : 배열 수가 일치해야 함

In [27]:
arr=np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
arr1=np.arange(20,29)
arr1

array([20, 21, 22, 23, 24, 25, 26, 27, 28])

In [29]:
arr+arr1

array([21, 23, 25, 27, 29, 31, 33, 35, 37])

In [30]:
# 제곱
np.square(arr)

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [31]:
# 제곱근
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        ])

In [32]:
# log
np.log(arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [33]:
# 배열 합하기
np.add(arr, arr1)

array([21, 23, 25, 27, 29, 31, 33, 35, 37])

In [34]:
# 배열 합
np.sum(arr)

np.int64(45)

## 배열 기초 통계량 

In [35]:
# 평균(mean) , 표준편차(std) , 최대(max) , 최소(min)

In [36]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
# 평균
np.mean(arr)

np.float64(5.0)

In [38]:
# 표준편차
np.std(arr)

np.float64(2.581988897471611)

In [39]:
# 최대
np.max(arr)

np.int64(9)

In [40]:
# 최소
np.min(arr)

np.int64(1)

In [41]:
import numpy as np

data = np.array([10, 20, 30, 40, 50, 60, 70])

In [42]:
print("합계:", np.sum(data))
print("평균:", np.mean(data))
print("중앙값:", np.median(data))
print("최댓값:", np.max(data))
print("최솟값:", np.min(data))
print("표준편차:", np.std(data))
print("분산:", np.var(data))
print("25% 백분위수:", np.percentile(data, 25))
print("75% 백분위수:", np.percentile(data, 75))

합계: 280
평균: 40.0
중앙값: 40.0
최댓값: 70
최솟값: 10
표준편차: 20.0
분산: 400.0
25% 백분위수: 25.0
75% 백분위수: 55.0
